import { PxlKitIcon, type PxlKitData } from '@pxlkit/core'

type IconName = 'journal' | 'profile' | 'chapter' | 'clue' | 'toolkit' | 'save' | 'quest'

interface Props {
  name: IconName
  label: string
  size?: number
}

const palette = {
  G: '#F7C85A',
  C: '#64E4FF',
  R: '#F05B72',
  B: '#1A2B55',
  W: '#F7EAC7',
  S: '#7C8FB8',
}

const icons: Record<IconName, PxlKitData> = {
  journal: {
    name: 'journal',
    size: 16,
    category: 'guild',
    tags: ['journal', 'book'],
    palette,
    grid: [
      '....GGGGGGGG....',
      '...GBBBBBBBG....',
      '..GBWWWWWWBG....',
      '..GBWCCCCWBG....',
      '..GBWCCCCWBG....',
      '..GBWWWWWWBG....',
      '..GBBBBBBBG....',
      '..GBWWWWWWBG....',
      '..GBWSSSSWBG....',
      '..GBWWWWWWBG....',
      '..GBWCCCCWBG....',
      '..GBWWWWWWBG....',
      '...GBBBBBBBG....',
      '....GGGGGGGG....',
      '................',
      '................',
    ],
  },
  profile: {
    name: 'profile',
    size: 16,
    category: 'guild',
    tags: ['profile', 'character'],
    palette,
    grid: [
      '................',
      '......GGGG......',
      '.....GWWWWG.....',
      '....GWRRWWG.....',
      '....GWWWWWG.....',
      '.....GWWG......',
      '......GG.......',
      '.....GBBG......',
      '....GBCCBG.....',
      '...GBCCCCBG....',
      '..GBCCCCCCBG...',
      '..GBCGGGGCBG...',
      '..GBG....GBG...',
      '...G......G....',
      '................',
      '................',
    ],
  },
  chapter: {
    name: 'chapter',
    size: 16,
    category: 'guild',
    tags: ['chapter', 'map'],
    palette,
    grid: [
      '................',
      '..GGGG....GGGG..',
      '.GCCCCG..GCCCCG.',
      '.GCSSCG..GCSSCG.',
      '.GCCCCGGGGCCCCG.',
      '.GCCCSSSSSCCCG..',
      '..GCCCCCCCCCG...',
      '...GGGCCCCG.....',
      '.....GCCCCGGG...',
      '...GGCCCCCCCCG..',
      '..GCCCSSSSSCCG..',
      '.GCCCCGGGGCCCCG.',
      '.GCSSCG..GCSSCG.',
      '.GCCCCG..GCCCCG.',
      '..GGGG....GGGG..',
      '................',
    ],
  },
  clue: {
    name: 'clue',
    size: 16,
    category: 'guild',
    tags: ['clue', 'spark'],
    palette,
    grid: [
      '................',
      '.......C........',
      '......CCC.......',
      '...C..CGC..C....',
      '....CCGGGCC.....',
      '.....GGGGG......',
      '..CCGGWWGGCC....',
      '...GGWWWWWG.....',
      '..CCGGWWGGCC....',
      '.....GGGGG......',
      '....CCGGGCC.....',
      '...C..CGC..C....',
      '......CCC.......',
      '.......C........',
      '................',
      '................',
    ],
  },
  toolkit: {
    name: 'toolkit',
    size: 16,
    category: 'guild',
    tags: ['toolkit', 'bag'],
    palette,
    grid: [
      '................',
      '.....GGGGGG.....',
      '....GBBBBBG.....',
      '...GBG..GBG.....',
      '..GBGGGGGGBG....',
      '..GBCCCCCCBG....',
      '..GBCGCCGCBG....',
      '..GBCCCCCCBG....',
      '..GBRRCCRRBG....',
      '..GBCCCCCCBG....',
      '..GBCCCCCCBG....',
      '...GBBBBBBG.....',
      '....GGGGGG......',
      '................',
      '................',
      '................',
    ],
  },
  save: {
    name: 'save',
    size: 16,
    category: 'guild',
    tags: ['save', 'slot'],
    palette,
    grid: [
      '................',
      '..GGGGGGGGGGGG..',
      '.GBBBBBBBBBBBBG.',
      '.GBCCCCCCCCCCBG.',
      '.GBCSSSSSSSSCBG.',
      '.GBCCCCCCCCCCBG.',
      '.GBBBBBBBBBBBBG.',
      '.GBGGGGGGGGGGBG.',
      '.GBGWWWWWWWWGBG.',
      '.GBGWRRRRRRWGBG.',
      '.GBGWWWWWWWWGBG.',
      '.GBGGGGGGGGGGBG.',
      '.GBBBBBBBBBBBBG.',
      '..GGGGGGGGGGGG..',
      '................',
      '................',
    ],
  },
  quest: {
    name: 'quest',
    size: 16,
    category: 'guild',
    tags: ['quest', 'board'],
    palette,
    grid: [
      '................',
      '..GGGGGGGGGGGG..',
      '.GBBBBBBBBBBBBG.',
      '.GBWWWWWWWWWWBG.',
      '.GBWCCCCCCCCWBG.',
      '.GBWWWWWWWWWWBG.',
      '.GBWSSSSSSSSWBG.',
      '.GBWWWWWWWWWWBG.',
      '.GBWCCCCCCCCWBG.',
      '.GBWWWWWWWWWWBG.',
      '.GBBBBBBBBBBBBG.',
      '..GGG......GGG..',
      '...G........G...',
      '...G........G...',
      '................',
      '................',
    ],
  },
}

export default function GuildPixelIcon({ name, label, size = 28 }: Props) {
  return <PxlKitIcon icon={icons[name]} size={size} aria-label={label} />
}

